apiVersion: v1
kind: ConfigMap
metadata:
  name: web-html
  namespace: prod
data:
  index.html: |
    <!doctype html>
    <html>
      <head><meta charset="utf-8"><title>Nolan — Minikube</title></head>
      <body style="font-family: system-ui; max-width: 720px; margin: 40px auto;">
        <h1>It works 🎉</h1>
        <p>Servi par NGINX dans Kubernetes (namespace <b>prod</b>).</p>
      </body>
    </html>
